### ISSUE TITLE
:warning: Calculator of expenses accepting numbers in Expense  field

### ISSUE THREAD

**Issue by ridabensalem** [DilsherB/react-budget-calculator#6]
Hi @DilsherB  you did a great job building this React budget Calculator :+1: , however, I have this note  : 

- The expense field should only accept text characters and should display an error message if a number is entered.currently it is accepting numbers 
- The UI could be better, I think you could add a  spacing between the expense and the amount fields.
Happy coding :smile:

**Comment by DilsherB** [comment]
> Hi @DilsherB you did a great job building this React budget Calculator 👍 , however, I have this note :
> 
>     * The expense field should only accept text characters and should display an error message if a number is entered.currently it is accepting numbers
> 
>     * The UI could be better, I think you could add a  spacing between the expense and the amount fields.
>       Happy coding 😄

Hi @ridabensalem,
Thank you very much for taking time to review my project. I'll address these issues definitely. 
Once again thanks a lot for your time/suggestion/efforts.

**Comment by ridabensalem** [comment]
My pleasure Dilsher :smile:

**Comment by DilsherB** [comment]
> My pleasure Dilsher 😄

So nice of you Mr. Rida,
I have applied validations, I also tried to show custom messages but face some difficulties if you have any idea, please help

**Comment by DilsherB** [comment]
@ridabensalem

**Comment by ridabensalem** [comment]
> > My pleasure Dilsher smile
> 
> So nice of you Mr. Rida, I have applied validations, I also tried to show custom messages but face some difficulties if you have any idea, please help

Yeah I would love to contribute to your application, could you please check your slack , I sent you a message about that

**Comment by DilsherB** [comment]
> > > My pleasure Dilsher smile
> > 
> > 
> > So nice of you Mr. Rida, I have applied validations, I also tried to show custom messages but face some difficulties if you have any idea, please help
> 
> Yeah I would love to contribute to your application, could you please check your slack , I sent you a message about that

@ridabensalem , 
I would like to tell you that a friend like you is an asset. Thank you for your interest and readiness to do help. 
I have done the custom validations.
Now I got an idea to give the user an option to select the currency
